name: Wails build

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build: [
          {name: wailsTest, platform: linux/amd64, os: ubuntu-latest},
          {name: wailsTest, platform: windows/amd64, os: windows-latest}
        ]
    runs-on: ${{ matrix.build.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: dAppServer/wails-build-action@v2.2
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
  macos:
   name:"Test Macos"
   runs-on:"macos-latest"
   steps:
     - uses:actions/checkout@v3
     - uses: actions/setup-go@v3
       with:
         go-version:'1.21.6'
     - uses: actions/setup-node@v3
       with:
         node-version:'20'
       run: npm install
       run: go install github.com/wailsapp/wails/v2/cmd/wails@latest
       run: wails build --platform darwin
